export { default } from './Sidebar.js';
import '../tslib.es6-905b4068.js';
import 'react/jsx-runtime';
import '@mui/material/Box';
import '@mui/material/List';
import './SidebarMenuItem.js';
import '@mui/material/Collapse';
import '@mui/icons-material/ExpandLess';
import '@mui/icons-material/ExpandMore';
import 'react';
import '../ColoredIconWrapper/ColoredIconWrapper.js';
import 'styled-components';
import '@mui/material/ListItemText';
import '@mui/material/ListItemIcon';
import 'react-router-dom';
import '@mui/material/Divider';
import '@mui/material/styles';
